# Generated by Django 5.2 on 2025-04-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
